name: CSharp CI

on: [push]

jobs:
    build_test:
        name: build test
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'
        - name: Run unit checks
          run: dotnet test Timesheet --filter FullyQualifiedName~Timesheet.Tests.Unit --logger trx --results-directory ./test-results
        - name: Run integration check
          run:
            dotnet run --project Timesheet &
            sleep 10 &&
            dotnet test Timesheet --filter FullyQualifiedName~Timesheet.Tests.Api --logger trx --results-directory ./test-results
        - name: Run E2E check
          run:
            dotnet run --project Timesheet &
            sleep 10 &&
            dotnet test Timesheet --filter FullyQualifiedName~Timesheet.Tests.E2EH --logger trx --results-directory ./test-results
        - name: Publish Test Results
          uses: EnricoMi/publish-unit-test-result-action/windows@v2
          if: always()
          with:
           files: |
             test-results/*.trx
